version: 0.1
phases:
  build:
    commands:
      - npm install
      - npm run build:prod
      - cp index.prod.html dist/index.html
artifacts:
  files:
    - dist/index.html
    - dist/js/*
    - dist/css/*
